"""fix: add images column as list of urls (JSONB) in products table

Revision ID: 0e8e293508c1
Revises: 389eca44a68c
Create Date: 2024-08-25 10:40:28.513820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e8e293508c1'
down_revision: Union[str, None] = '389eca44a68c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('products', 'product_image')
    op.drop_column('products', 'product_image_header')
    op.drop_column('products', 'stock_quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock_quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('product_image_header', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('product_image', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('products', 'images')
    # ### end Alembic commands ###
