"""feat: add images for user profiles

Revision ID: 167c82f15048
Revises: b31781beb618
Create Date: 2024-08-18 23:49:02.270876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '167c82f15048'
down_revision: Union[str, None] = 'b31781beb618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('image', sa.LargeBinary(), nullable=True))
    op.add_column('customers', sa.Column('image_header', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'image_header')
    op.drop_column('customers', 'image')
    # ### end Alembic commands ###
