"""hopefully final attempt at adding base tables

Revision ID: 315372bd8bb3
Revises: 3e7932f90870
Create Date: 2024-08-13 10:52:00.015635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '315372bd8bb3'
down_revision: Union[str, None] = '3e7932f90870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('customers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('gender', sa.Enum('M', 'F', name='genders'), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('image_header', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customers')
    op.drop_table('users')
    # ### end Alembic commands ###
