"""make name compulsory for every user

Revision ID: 8a3672762b43
Revises: 315372bd8bb3
Create Date: 2024-08-13 10:56:27.275761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a3672762b43'
down_revision: Union[str, None] = '315372bd8bb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'first_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('customers', 'last_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('customers', 'last_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('customers', 'first_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###
