"""feat: add measurements table and relationships

Revision ID: 92d64b81e728
Revises: 975e0e57461c
Create Date: 2024-08-18 23:40:28.165698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92d64b81e728'
down_revision: Union[str, None] = '975e0e57461c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'image')
    op.drop_column('customers', 'image_header')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('image_header', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('image', postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
