"""fix: restructure user/customer db... move fname lname to user

Revision ID: 975e0e57461c
Revises: f3df9edfbd2f
Create Date: 2024-08-18 13:33:51.370663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '975e0e57461c'
down_revision: Union[str, None] = 'f3df9edfbd2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
