"""feat: add measurements table and relationships the right way

Revision ID: b31781beb618
Revises: 92d64b81e728
Create Date: 2024-08-18 23:42:16.422659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b31781beb618'
down_revision: Union[str, None] = '92d64b81e728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurements',
    sa.Column('id', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('round_head', sa.Float(), nullable=True),
    sa.Column('neck', sa.Float(), nullable=True),
    sa.Column('shoulder', sa.Float(), nullable=True),
    sa.Column('sleeve', sa.Float(), nullable=True),
    sa.Column('flexed_biceps', sa.Float(), nullable=True),
    sa.Column('wrist', sa.Float(), nullable=True),
    sa.Column('back', sa.Float(), nullable=True),
    sa.Column('front_chest', sa.Float(), nullable=True),
    sa.Column('chest', sa.Float(), nullable=True),
    sa.Column('stomach', sa.Float(), nullable=True),
    sa.Column('hip', sa.Float(), nullable=True),
    sa.Column('waist', sa.Float(), nullable=True),
    sa.Column('crotch', sa.Float(), nullable=True),
    sa.Column('thigh', sa.Float(), nullable=True),
    sa.Column('knee', sa.Float(), nullable=True),
    sa.Column('ankle', sa.Float(), nullable=True),
    sa.Column('pant_length', sa.Float(), nullable=True),
    sa.Column('inseam', sa.Float(), nullable=True),
    sa.Column('front_view_image', sa.LargeBinary(), nullable=True),
    sa.Column('front_view_image_header', sa.String(), nullable=True),
    sa.Column('side_view_image', sa.String(), nullable=True),
    sa.Column('side_view_image_header', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id', 'customer_id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurements')
    # ### end Alembic commands ###
