"""fix: make gender column nullable

Revision ID: f3df9edfbd2f
Revises: 8a3672762b43
Create Date: 2024-08-13 13:39:07.157885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3df9edfbd2f'
down_revision: Union[str, None] = '8a3672762b43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
